title: Talk Data to Me
author: Missyahsa
email: melissakwert@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
Blog about useful data presentations and how to tell a story from the data.

# social links
github_username:  mkwert # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
